In [ ]:
#didn't work
#from mat4py import loadmat
#data = loadmat(filename)
#print(type(data))

In [35]:
import scipy.io
import numpy as np

path = "C:/Users/nat/quantum/gic/Auditory_cortex_data/Auditory cortex data/031020_367n_100um20st_FRA/"
file = "allPlanesVariables27-Feb-2021.mat"
filename = path + file

print(filename)

mat = scipy.io.loadmat(filename)

print(type(mat))

print(mat.keys())

C:/Users/nat/quantum/gic/Auditory_cortex_data/Auditory cortex data/031020_367n_100um20st_FRA/allPlanesVariables27-Feb-2021.mat
<class 'dict'>
dict_keys(['__header__', '__version__', '__globals__', 'BFinfo', 'CellInfo', 'CorrInfo', 'allZCorrInfo', 'allxc', 'allyc', 'allzc', 'exptVars', 'selectZCorrInfo', 'stimInfo', 'zDFF', 'zStuff', '__function_workspace__'])


In [109]:
216+241+263+234+226

1180

In [96]:
print(mat["__header__"])
print(mat["__version__"])
print(mat["__globals__"])
print(mat["exptVars"])
print(len(mat["exptVars"]))
print(mat["exptVars"])
#print(mat["stimInfo"])

b'MATLAB 5.0 MAT-file, Platform: PCWIN64, Created on: Thu Feb 25 18:09:37 2021'
1.0
[]
[[(array([[512]], dtype=uint16), array([[512]], dtype=uint16), array([[35000]], dtype=uint16), array([[0.721]]), array([[30]], dtype=uint8), array([[1]], dtype=uint8), array([[20]], dtype=uint8), array([[6]], dtype=uint8), array([[7]], dtype=uint8), array([[5000]], dtype=uint16), array([[524288]], dtype=int32))]]
1
[[(array([[512]], dtype=uint16), array([[512]], dtype=uint16), array([[35000]], dtype=uint16), array([[0.721]]), array([[30]], dtype=uint8), array([[1]], dtype=uint8), array([[20]], dtype=uint8), array([[6]], dtype=uint8), array([[7]], dtype=uint8), array([[5000]], dtype=uint16), array([[524288]], dtype=int32))]]


In [108]:
print(len(mat["zStuff"]))
print(len(mat["zStuff"][0]))
print(len(mat["zStuff"][0][1]))
exptFreq = mat["zStuff"][0][1][6]
print(len(exptFreq))
print(exptFreq[0])
unique_values, counts = np.unique(exptFreq, return_counts=True)
print(unique_values)
print(counts)
count_nonzero = (exptFreq != 0).sum()
print(count_nonzero)

1
7
8
5000
[0.]
[ 0.     3.     4.243  6.     8.485 12.    16.971 24.    33.941 48.   ]
[3452  174  171  170  170  175  173  172  170  173]
1548


In [93]:
print(len(mat["allxc"]))
print(mat["allxc"][0])
print(len(mat["allxc"][1][0]))
print(len(mat["allxc"][2][0]))
print(mat["allxc"][1][0][0])
print(mat["allxc"][1][0][225])

7
[array([], shape=(1, 0), dtype=float64)]
226
234
[104.88805082]
[150.27266263]


In [43]:
print(len(mat["zDFF"]))
print(mat["zDFF"][0])

7
[array([], shape=(1, 0), dtype=float64)]


In [63]:
print(len(mat["zDFF"][1]))
print(len(mat["zDFF"][1][0]))
print(len(mat["zDFF"][1][0][0]))
print(mat["zDFF"][1][0][0][0])
print(mat["zDFF"][1][0][0])
print(len(mat["zDFF"][2][0]))

1
226
5000
-1.1428363490789186
[-1.14283635 30.6557832  46.786738   ... 29.6246575  35.82626946
 15.97226964]
234


In [37]:
corrInfo = mat["CorrInfo"]
print(type(corrInfo))
print(len(corrInfo))
print(len(corrInfo[0]))

<class 'numpy.ndarray'>
1
7


In [18]:
print(corrInfo[0])

[(array([], shape=(1, 0), dtype=float64), array([], shape=(1, 0), dtype=float64), array([], shape=(1, 0), dtype=float64))
 (array([[        nan, -0.00700899,  0.6692444 , ..., -0.42630639,
          0.1413568 , -0.20710354],
        [        nan,         nan,  0.37346904, ...,  0.29403838,
         -0.71456363, -0.02952375],
        [        nan,         nan,         nan, ...,  0.2360714 ,
         -0.21987325, -0.08282106],
        ...,
        [        nan,         nan,         nan, ...,         nan,
         -0.11199153,  0.4061487 ],
        [        nan,         nan,         nan, ...,         nan,
                 nan,  0.54974884],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan]], shape=(226, 226)), array([[[        nan,         nan,         nan, ...,         nan,
                  nan,         nan],
         [-0.07676429, -0.17766772,  0.15362491, ...,  0.50135896,
          -0.33600466,  0.32587586],
         [-0.37553428,  0

In [24]:
print(len(corrInfo[0][1]))

3


In [28]:
p1_0 = corrInfo[0][1][0]
p1_1 = corrInfo[0][1][1]
p1_2 = corrInfo[0][1][2]

In [29]:
p1_0

array([[        nan, -0.00700899,  0.6692444 , ..., -0.42630639,
         0.1413568 , -0.20710354],
       [        nan,         nan,  0.37346904, ...,  0.29403838,
        -0.71456363, -0.02952375],
       [        nan,         nan,         nan, ...,  0.2360714 ,
        -0.21987325, -0.08282106],
       ...,
       [        nan,         nan,         nan, ...,         nan,
        -0.11199153,  0.4061487 ],
       [        nan,         nan,         nan, ...,         nan,
                nan,  0.54974884],
       [        nan,         nan,         nan, ...,         nan,
                nan,         nan]], shape=(226, 226))

In [36]:
np.nanmean(p1_0)

np.float64(0.04882897406071039)

In [30]:
p1_1

array([[[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [-0.07676429, -0.17766772,  0.15362491, ...,  0.50135896,
         -0.33600466,  0.32587586],
        [-0.37553428,  0.15118976,  0.27289314, ...,  0.37300915,
         -0.17022198, -0.12794476],
        ...,
        [-0.32257133, -0.22654626, -0.33549153, ...,  0.4425303 ,
          0.07949574, -0.29977822],
        [-0.19699042, -0.42723131,  0.01863064, ...,  0.2661974 ,
          0.13500756,  0.29949092],
        [-0.18787125,  0.13339224,  0.54992928, ..., -0.11561827,
          0.04603457,  0.39569705]],

       [[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [-0.13100744,  0.08094256,  0.12213244, ...,  0.42023742,
         -0.06911435,  0.06964065],
        ...,
        [ 0.43227376, -0.17413079,  0.07414681, ...,  

In [32]:
p1_2

array([[        nan,  0.24558848,  0.2189861 , ...,  0.15509671,
         0.10170343,  0.10456673],
       [        nan,         nan,  0.30045794, ...,  0.40644968,
         0.0332497 ,  0.25024268],
       [        nan,         nan,         nan, ...,  0.09366078,
         0.01830668, -0.0273404 ],
       ...,
       [        nan,         nan,         nan, ...,         nan,
         0.1079711 ,  0.16647678],
       [        nan,         nan,         nan, ...,         nan,
                nan,  0.16289556],
       [        nan,         nan,         nan, ...,         nan,
                nan,         nan]], shape=(226, 226))