In [1]:
import numpy as np
from numpy.linalg import eig
from qiskit import QuantumCircuit
from qiskit_algorithms import IterativePhaseEstimation
from qiskit.primitives import Sampler

In [2]:
num_iterations = 3
sampler = Sampler()
ipe = IterativePhaseEstimation(num_iterations, sampler)

In [3]:
num_qubits = 2
unitary_matrix = np.array([[1, 0, 0, 0], [0, 0, -1, 0], [0, -1, 0, 0], [0, 0, 0, 1]])
print("unitary matrix:\n", unitary_matrix)
eig_value, eig_vector = eig(unitary_matrix)
print("eigenvalue:", eig_value)
print("eigenvector:", eig_vector)

unitary matrix:
 [[ 1  0  0  0]
 [ 0  0 -1  0]
 [ 0 -1  0  0]
 [ 0  0  0  1]]
eigenvalue: [ 1. -1.  1.  1.]
eigenvector: [[ 0.          0.          1.          0.        ]
 [-0.70710678  0.70710678  0.          0.        ]
 [ 0.70710678  0.70710678  0.          0.        ]
 [ 0.          0.          0.          1.        ]]


In [4]:
# check if the unitary_matrix is actually unitary
np.allclose(np.eye(len(unitary_matrix)), unitary_matrix.dot(unitary_matrix.T.conj()))

True

In [5]:
unitary_operator = QuantumCircuit(num_qubits)
unitary_operator.unitary(unitary_matrix, [0, 1])
print(type(unitary_operator))

<class 'qiskit.circuit.quantumcircuit.QuantumCircuit'>


In [6]:
ansatz = QuantumCircuit(num_qubits)

In [7]:
result = ipe.estimate(unitary_operator, ansatz)
eigenvalue = np.exp(2*np.pi*result.phase)
print("phase:", result.phase)
print("eigenvalue:", eigenvalue)

phase: 0.0
eigenvalue: 1.0


#### Single qubit S-gate example

In [8]:
# single qubit S-gate
unitary_matrix = np.array([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, np.exp(complex(0,np.pi/2))]])
print("unitary matrix:\n", unitary_matrix)
eig_value, eig_vector = eig(unitary_matrix)
print("eigenvalue:\n", eig_value)
print("eigenvector:\n", eig_vector)

unitary matrix:
 [[1.000000e+00+0.j 0.000000e+00+0.j 0.000000e+00+0.j 0.000000e+00+0.j]
 [0.000000e+00+0.j 1.000000e+00+0.j 0.000000e+00+0.j 0.000000e+00+0.j]
 [0.000000e+00+0.j 0.000000e+00+0.j 1.000000e+00+0.j 0.000000e+00+0.j]
 [0.000000e+00+0.j 0.000000e+00+0.j 0.000000e+00+0.j 6.123234e-17+1.j]]
eigenvalue:
 [1.000000e+00+0.j 1.000000e+00+0.j 1.000000e+00+0.j 6.123234e-17+1.j]
eigenvector:
 [[1.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 1.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 1.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 1.+0.j]]


In [9]:
# check if the unitary_matrix is actually unitary
np.allclose(np.eye(len(unitary_matrix)), unitary_matrix.dot(unitary_matrix.T.conj()))

True

In [10]:
unitary_operator = QuantumCircuit(2)
unitary_operator.unitary(unitary_matrix, [0, 1])
print(type(unitary_operator))

<class 'qiskit.circuit.quantumcircuit.QuantumCircuit'>


In [11]:
ansatz = QuantumCircuit(2)
ansatz.x(1)
print(type(ansatz))

<class 'qiskit.circuit.quantumcircuit.QuantumCircuit'>


In [12]:
result = ipe.estimate(unitary_operator, ansatz)
eigenvalue = np.exp(2*np.pi*result.phase)
print("phase:", result.phase)
print("eigenvalue:", eigenvalue)

phase: 0.0
eigenvalue: 1.0
