In [1]:
import numpy as np
import scipy.linalg as la

In [12]:
A = np.array([[1, 0], [0, 1]])
# extract eigenvalues 1 and 1, and eigenvectors [1, 0] and [0, 1] from A
eigen_values, eigen_vectors = la.eig(A)
print(eigen_values)
print(eigen_vectors)

[1.+0.j 1.+0.j]
[[1. 0.]
 [0. 1.]]


In [23]:
from sympy import Matrix
print("A is diag:", Matrix(A).is_diagonalizable())
B = np.array([[1, 1], [0, 1]])
print("B is diag:", Matrix(B).is_diagonalizable())

A is diag: True
B is diag: False


In [26]:
expA = la.expm(A)
expA

array([[2.71828183, 0.        ],
       [0.        , 2.71828183]])

In [35]:
import math
print(math.exp(0), math.exp(1), math.exp(10))

1.0 2.718281828459045 22026.465794806718


In [33]:
C = np.array([[1, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 1]])
expC = la.expm(C)
expC

array([[2.71828183, 0.        , 0.        , 0.        ],
       [0.        , 1.        , 0.        , 0.        ],
       [0.        , 0.        , 1.        , 0.        ],
       [0.        , 0.        , 0.        , 2.71828183]])